language: node_js

sudo: true

addons:
  chrome: beta

node_js:
  - '8'
  - '10'

branches:
  only:
  - master

cache: yarn

matrix:
  fast_finish: true

install:
  - npm install

notifications:
  email: true

script:
  - npm run test
